# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



User.destroy_all
Game.destroy_all
Chatroom.destroy_all
UserGame.destroy_all
file = URI.open('https://tse1.explicit.bing.net/th?id=OIP.QbYQOLvF6Mm5YRMwKHnxUAHaHa&pid=Api')
user1 = User.create!(email: '1234567@gmail.com', password: 'azerty63-1', username: 'tbayard', address: '230 rue paul bert, Lyon', zipcode: '69003', player: true, trader: false)
user1.image.attach(io: file, filename: '1.png', content_type: 'image/png')
file = URI.open('https://www.empireposter.de/bilder/bilder_XL/845023.jpg')
user2 = User.create!(email: '123456@gmail.com', password: 'azerty63-1', username: 'thenriet', address: '100 Rue Chevreul, Lyon', zipcode: '69007', player: true, trader: false)
user2.image.attach(io: file, filename: '2.png', content_type: 'image/png')
file = URI.open('https://images.unsplash.com/photo-1620336655071-6b2ea4272b15?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80')
user3 = User.create!(email: '123789@gmail.com', password: 'azerty63-1', username: 'ltoschini', address: '84 Rue du Pensionnat, Lyon', zipcode: '69003', player: false, trader: true, trader_score: 36, trust_score: 32)
user3.image.attach(io: file, filename: '3.png', content_type: 'image/png')
file = URI.open('https://tse2.mm.bing.net/th?id=OIP.v1IrDjTXpjlqnmfvkgBtzAHaFc&pid=Api')
user4 = User.create!(email: '5867494@gmail.com', password: 'azerty63-1', username: 'ldelpino', address: '238 rue paul bert, Lyon', zipcode: '69003', player: true, trader: false, player_score: 12, trust_score: 11)
user4.image.attach(io: file, filename: '5.png', content_type: 'image/png')
file = URI.open('https://images.unsplash.com/photo-1683754014434-c29725586730?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80')
user5 = User.create!(email: '4948585875@gmail.com', password: 'azerty63-1', username: 'atournay', address: '256 Rue Chevreul, Lyon', zipcode: '69007', player: true, trader: false, player_score: 5, trust_score: 4)
user5.image.attach(io: file, filename: '6.png', content_type: 'image/png')
file = URI.open('https://www.pixel-creation.com/wp-content/uploads/magic-the-gathering-weapons-armor-artwork-planeswalker-free.png')
user6 = User.create!(email: '0983737@gmail.com', password: 'azerty63-1', username: 'tbonny', address: '12 Avenue Georges Pompidou, Lyon', zipcode: '69003', player: false, trader: true, trader_score: 124, trust_score: 120)
user6.image.attach(io: file, filename: '8.png', content_type: 'image/png')
file = URI.open('http://noemie08.n.o.pic.centerblog.net/ea63b5c9.png')
user7 = User.create!(email: '3489489@gmail.com', password: 'azerty63-1', username: 'hpierre', address: '9 Rue du Pensionnat, Lyon', zipcode: '69003', player: false, trader: true, trader_score: 2, trust_score: 2)
user7.image.attach(io: file, filename: '7.png', content_type: 'image/png')
file = URI.open('http://noemie08.n.o.pic.centerblog.net/295098b3.png')
user8 = User.create!(email: '1231011@gmail.com', password: 'azerty63-1', username: 'odebienne', address: '21 Avenue Georges Pompidou, Lyon', zipcode: '69003', player: false, trader: true, trader_score: 79, trust_score: 79)
user8.image.attach(io: file, filename: '4.png', content_type: 'image/png')
file = URI.open('http://images6.fanpop.com/image/photos/36200000/Madara-Uchiha-image-madara-uchiha-36213178-1600-1906.jpg')
user9 = User.create!(email: '987@gmail.com', password: 'azerty63-1', username: 'abonnard', address: '100 rue sainte catherine, Bordeaux', zipcode: '33000', player: true, trader: false, player_score: 23, trust_score: 23)
user9.image.attach(io: file, filename: '9.png', content_type: 'image/png')
file = URI.open('https://www.modern-notoriety.com/wp-content/uploads/2019/03/coa.jpg')
user10 = User.create!(email: '876@gmail.com', password: 'azerty63-1', username: 'lailefr', address: '20 Cr Pasteur, Bordeaux', zipcode: '33000', player: false, trader: true, trader_score: 46, trust_score: 46)
user10.image.attach(io: file, filename: '10.png', content_type: 'image/png')
file = URI.open('https://yt3.ggpht.com/a-/AAuE7mBmmL0JI99vOuc5J7Pgrs4yTVcZw7gbXYt0=s900-mo-c-c0xffffffff-rj-k-no')
user11 = User.create!(email: '765@gmail.com', password: 'azerty63-1', username: 'spapadakis', address: '44 Cr Aristide Briand', zipcode: '33800', player: true, trader: false, player_score: 21, trust_score: 21)
user11.image.attach(io: file, filename: '11.png', content_type: 'image/png')
file = URI.open('https://wallpapercave.com/wp/wp7055887.png')
user12 = User.create!(email: '654@gmail.com', password: 'azerty63-1', username: 'clombardo', address: 'Place des Capucins, Bordeaux', zipcode: '33800', player: false, trader: true, trader_score: 48, trust_score: 48)
user12.image.attach(io: file, filename: '12.png', content_type: 'image/png')
file = URI.open('https://yt3.ggpht.com/a/AGF-l7-VPpztXdyLrfggbPA1JqCJcU9itsFhgsX89g=s900-c-k-c0xffffffff-no-rj-mo')
user13 = User.create!(email: '543@gmail.com', password: 'azerty63-1', username: 'zyroxx', address: '180 Rue de Saint Genès, Bordeaux', zipcode: '33000', player: true, trader: false, player_score: 67, trust_score: 67)
user13.image.attach(io: file, filename: '13.png', content_type: 'image/png')
file = URI.open('https://i.ytimg.com/vi/6iw7JZwXwbA/maxresdefault.jpg')
user14 = User.create!(email: '432@gmail.com', password: 'azerty63-1', username: 'faker', address: '110 Quai de Paludate, Bordeaux', zipcode: '33800', player: false, trader: true, trader_score: 98, trust_score: 98)
user14.image.attach(io: file, filename: '14.png', content_type: 'image/png')
file = URI.open('https://www.nawpic.com/media/2020/hisoka-nawpic-2-e1608667586770.jpg')
user15 = User.create!(email: '321@gmail.com', password: 'azerty63-1', username: 'inox', address: '10 Place du 14 Juillet, Bègles', zipcode: '33130', player: true, trader: false, player_score: 87, trust_score: 87)
user15.image.attach(io: file, filename: '15.png', content_type: 'image/png')
file = URI.open('https://wallup.net/wp-content/uploads/2017/11/23/531492-Magic_The_Gathering.jpg')
user16 = User.create!(email: '3431012@gmail.com', password: 'azerty63-1', username: 'magicking', address: '10 rue de la Bassée, Lille', zipcode: '59800', player: true, trader: true, player_score: 20, trust_score: 20)
user16.image.attach(io: file, filename: '16.png', content_type: 'image/png')
file = URI.open('https://images.unsplash.com/photo-1596743343697-bd2c1e5a8c81?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80')
user17 = User.create!(email: '3431011@gmail.com', password: 'azerty63-1', username: 'meilleurquetoi', address: '8 rue de la clé, Lille', zipcode: '59800', player: false, trader: true, trader_score: 17, trust_score: 17)
user17.image.attach(io: file, filename: '17.png', content_type: 'image/png')
file = URI.open('https://tse2.mm.bing.net/th?id=OIP.6NVYspPB8heSlKpZg850tgHaEK&pid=Api')
user18 = User.create!(email: '3431010@gmail.com', password: 'azerty63-1', username: 'bibiche', address: '16 rue Solférino, Lille', zipcode: '59800', player: true, trader: false, player_score: 20, trust_score: 20)
user18.image.attach(io: file, filename: '18.png', content_type: 'image/png')
file = URI.open('https://images.unsplash.com/photo-1590955559496-50316bd28ff2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1511&q=80')
user19 = User.create!(email: '3431019@gmail.com', password: 'azerty63-1', username: 'thesorcerer', address: '20 rue Royale, Lille', zipcode: '59800', player: true, trader: true, trader_score: 42, player_score: 25, trust_score: 67)
user19.image.attach(io: file, filename: '19.png', content_type: 'image/png')
file = URI.open('https://images.unsplash.com/photo-1611931960487-4932667079f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80')
user20 = User.create!(email: '3431013@gmail.com', password: 'azerty63-1', username: 'fifidu62', address: '20 rue Montaigne, Liévin', zipcode: '62800', player: false, trader: true, trader_score: 110, trust_score: 110)
user20.image.attach(io: file, filename: '20.png', content_type: 'image/png')
file = URI.open('https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png')
user21 = User.create!(email: '1231012@gmail.com', password: 'azerty63-1', username: 'maximator', address: '34 Rue des Minimes, Douai', zipcode: '59500', player: true, trader: true, player_score: 10, trader_score: 0, trust_score: 10)
user21.image.attach(io: file, filename: '21.png', content_type: 'image/png')
file = URI.open('https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png')
user22 = User.create!(email: '1231013@gmail.com', password: 'azerty63-1', username: 'realtalk', address: '36 Avenue du Champ de Foire, Abbeville', zipcode: '80100', player: true, trader: false, player_score: 5, trust_score: 5)
user22.image.attach(io: file, filename: '22.png', content_type: 'image/png')
file = URI.open('https://static.posters.cz/image/1300/affiches-et-posters/magic-the-gathering-ajani-i86761.jpg')
user23 = User.create!(email: '1231014@gmail.com', password: 'azerty63-1', username: 'mistercash', address: '38 Rue Thibaudeau, Poitiers', zipcode: '86000', player: true, trader: false, player_score: 7, trader_score: 0, trust_score: 7)
user23.image.attach(io: file, filename: '23.png', content_type: 'image/png')
file = URI.open('https://www.mondespersistants.com/wp-content/uploads/2021/12/Daybreak-Games-publiera-Magic-The-Gathering-Online-en-2022.jpg')
user24 = User.create!(email: '1231015@gmail.com', password: 'azerty63-1', username: 'ledestroyer', address: '70 Rue André Theuriet, Clermont-Ferrand', zipcode: '63000', player: false, trader: true, trader_score: 15, trust_score: 15)
user24.image.attach(io: file, filename: '24.png', content_type: 'image/png')
file = URI.open('https://geek-mexicain.net/thumbs/730x350c/p/magic-the-gathering-quelques-bases/magic-the-gathering-quelques-bases.jpg')
user25 = User.create!(email: '1231016@gmail.com', password: 'azerty63-1', username: 'chamouille', address: '1 Rue Parguez, Besançon', zipcode: '25000', player: false, trader: true, trader_score: 5, trust_score: 5)
user25.image.attach(io: file, filename: '25.png', content_type: 'image/png')
file = URI.open('https://images.unsplash.com/photo-1628968434441-d9c1c66dcde7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80')
user26 = User.create!(email: '00000@gmail.com', password: 'azerty63-1', username: 'Lemarcheurblanc', address: '20 Rue Thiers,  Liévin', zipcode: '62800', player: true, trader: true, trader_score: 30, player_score: 20, trust_score: 50)
user26.image.attach(io: file, filename: '26.png', content_type: 'image/png')
file = URI.open('https://media.magic.wizards.com/images/hero/EMA_Header_Image.jpg')
user27 = User.create!(email: '000001@gmail.com', password: 'azerty63-1', username: 'Thibautbgdu69', address: '10 Rue Du Pouech, Saint-Gaudens', zipcode: '31800', player: true, trader: false, player_score: 13, trust_score: 13)
user27.image.attach(io: file, filename: '27.png', content_type: 'image/png')
file = URI.open('https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/11/prossh.jpg')
user28 = User.create!(email: '000002@gmail.com', password: 'azerty63-1', username: 'Thomaslebg', address: '18 Avenue Des Cordeliers,  La Rochelle', zipcode: '17000', player: true, trader: true, trader_score: 16, player_score: 25, trust_score: 41)
user28.image.attach(io: file, filename: '28.png', content_type: 'image/png')
file = URI.open('https://images.alphacoders.com/943/thumb-1920-943281.jpg')
user29 = User.create!(email: '000003@gmail.com', password: 'azerty63-1', username: 'OndinePrincesse', address: '5 Rue Du Moulin,  Oberhausbergen', zipcode: '67205', player: true, trader: false, player_score: 1, trust_score: 1)
user29.image.attach(io: file, filename: '29.png', content_type: 'image/png')
file = URI.open('https://static1.thegamerimages.com/wordpress/wp-content/uploads/2020/07/muxus.jpg')
user30 = User.create!(email: '000004@gmail.com', password: 'azerty63-1', username: 'user2310', address: 'Palais de l\'Élysée, 55 rue du Faubourg Saint-Honoré, Paris', zipcode: '75008', player: false, trader: true, trader_score: 110, trust_score: 110)
user30.image.attach(io: file, filename: '30.png', content_type: 'image/png')


Chatroom.create!( name: 'Discussion générale' )

game1 = Game.create!(name: 'Yugioh', description: "C'est l'heure du duel !", image: 'https://s2.qwant.com/thumbr/0x380/f/f/433eb09539e29fd08ba47442cee13b9bd66bfa3c8b757aec3ffe7fedc956f5/thumb-1920-128973.jpg?u=https%3A%2F%2Favatarfiles.alphacoders.com%2F128%2Fthumb-1920-128973.jpg&q=0&b=1&p=0&a=0')
game2 = Game.create!(name: 'Pokemon', description: 'Attrapez-les tous !', image: 'https://s1.qwant.com/thumbr/0x0/2/a/7ce5e058c891719d437de02574f3f596fd105bbf56326b1c4f2a0b37d9480b/Pikachu-01-pokemon-svg-cut-file-free-300x300.jpg?u=https%3A%2F%2Fwww.svgfiles.us%2Fwp-content%2Fuploads%2FPikachu-01-pokemon-svg-cut-file-free-300x300.jpg&q=0&b=1&p=0&a=0')
game3 = Game.create!(name: 'Magic The Gathering', description: 'La grandeur à tout prix !', image: 'https://s1.qwant.com/thumbr/0x380/3/f/00c9024d03ae676f7ed653016c4872fb2c7a8b787c57dfd83342786f7b4798/MTGlogo-font.jpg?u=https%3A%2F%2Ffontmeme.com%2Fimages%2FMTGlogo-font.jpg&q=0&b=1&p=0&a=0')

UserGame.create!(user: user1, game: game1)
UserGame.create!(user: user2, game: game1)
UserGame.create!(user: user3, game: game1)
UserGame.create!(user: user4, game: game2)
UserGame.create!(user: user5, game: game2)
UserGame.create!(user: user6, game: game2)
UserGame.create!(user: user7, game: game3)
UserGame.create!(user: user8, game: game3)
UserGame.create!(user: user9, game: game1)
UserGame.create!(user: user10, game: game1)
UserGame.create!(user: user11, game: game1)
UserGame.create!(user: user12, game: game1)
UserGame.create!(user: user13, game: game1)
UserGame.create!(user: user14, game: game1)
UserGame.create!(user: user15, game: game1)
UserGame.create!(user: user16, game: game2)
UserGame.create!(user: user17, game: game2)
UserGame.create!(user: user18, game: game3)
UserGame.create!(user: user19, game: game3)
UserGame.create!(user: user20, game: game3)
UserGame.create!(user: user21, game: game2)
UserGame.create!(user: user22, game: game2)
UserGame.create!(user: user23, game: game3)
UserGame.create!(user: user24, game: game3)
UserGame.create!(user: user25, game: game3)
UserGame.create!(user: user26, game: game3)
UserGame.create!(user: user27, game: game3)
UserGame.create!(user: user28, game: game3)
UserGame.create!(user: user29, game: game3)
UserGame.create!(user: user30, game: game3)
